; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-43-waveshare]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_protocol = espota
upload_port = 192.168.100.194

board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.filesystem = littlefs

;CAMBIE 0 -> 1
build_flags =
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    ;moononournation/GFX Library for Arduino
    moononournation/GFX Library for Arduino @ 1.4.0
    tamctec/TAMC_GT911
    https://github.com/enudenki/esp32-usb-host-midi-library.git

lib_ldf_mode = deep+
